### ISSUE TITLE
TerminusDB Docs: New page - Glossary

### ISSUE THREAD

**Issue by mark-terminusdb** [terminusdb/terminusdb-docs#10]
A glossary ideally with examples where possible.

**Some examples terms requiring definition/clarification** 
Product, predicate, organization, server, document, subdocument, document properties, other properties, enum, class, object, label, entity, layer, leaf, domain, subdomain, boundary, property, relationship, element, database, datastore, repository, etc., any others? 

**Object composition diagram**
In addition to examples, an object composition diagram (hand-drawn)would be beneficial illustrating how some of these terms interact/interrelate.

**Comment by matko** [comment]
Mark will plan a meeting for this this week.

**Comment by Francesca-Bit** [comment]
ok,perfect

**Comment by spl** [comment]
@GavinMendelGleason and @mark-terminusdb will meet about this. @mark-terminusdb will put together a template.
