### ISSUE TITLE
Migrate diff and patch client tutorial to GitBook

### ISSUE THREAD

**Issue by mark-terminusdb** [terminusdb/terminusdb-docs#103]
https://github.com/terminusdb/terminusdb-tutorials/tree/diff_patch/diff_patch

The current tutorial on GitHub is a great step forward. Consider the following to make the tutorial clearer for JavaScript and Python developers:

- The Python example using a simple `Person` document object is a perfect starting point. The tutorial will benefit from JavaScript and MongoDB (+Python and JavaScript) versions of the same example.
-  Similarly, it'll be great to demonstrate the more detailed kitchen appliance/food use case across all formats as well - Python, JavaScript, MongoDB + Python, MongoDB + JavaScript.

**Comment by spl** [comment]
@Neelterminusdb will look into this.
