### ISSUE TITLE
Migrate client reference guides to GitBook

### ISSUE THREAD

**Issue by mark-terminusdb** [terminusdb/terminusdb-docs#104]
# JavaScript
* https://terminusdb.github.io/terminusdb-client-js/#/
* `md` and `js` files in https://github.com/terminusdb/terminusdb-client-js/tree/main/docs
* Auto-generated by `createDocs.js`

# Python
* https://terminusdb.github.io/terminusdb-client-python/
* `md` and  `py` files in https://github.com/terminusdb/terminusdb-client-python/tree/master/docs
* Auto-generated by **?*

**Comment by Neelterminusdb** [comment]
Right now the JavaScript client reference docs will create a PR automatically when there is a change in the client docs
