### ISSUE TITLE
TerminusDB Docs: Existing page - How To->Query

### ISSUE THREAD

**Issue by mark-terminusdb** [terminusdb/terminusdb-docs#11]
Review/test accuracy of code segments:

- [x] **Query->Math operations** <https://docs.terminusdb.com/v4.2/#/How_To/math_query>

- [x] **Query->Do a graph query** <https://docs.terminusdb.com/v4.2/#/How_To/graph_query>

- [x] **Query->Save a query** <https://docs.terminusdb.com/v4.2/#/How_To/save_query>

- [ ] **Query->Constructing a JSON-LD query**<https://docs.terminusdb.com/v4.2/#/How_To/jsonld_query>

- [x] **Query->Use regex** <https://docs.terminusdb.com/v4.2/#/How_To/use_regex>

**Comment by GavinMendelGleason** [comment]
We should remove the JSON-LD query bit.
