### ISSUE TITLE
Refer to SPARQL in docs 

### ISSUE THREAD

**Issue by mark-terminusdb** [terminusdb/terminusdb-docs#129]
Potentially at this location: 

https://terminusdb.com/blog/the-power-of-web-object-query-language/

**Comment by luke-feeney** [comment]
if in the blog, it won't be picked up by searches in the docs. Maybe revive an FAQ?

**Comment by spl** [comment]
We should say something (like an FAQ) to the effect of: We don't support SPARQL, but we do implement WOQL, which is better and has a shorter name.

**Comment by spl** [comment]
@mark-terminusdb says the glossary would be the perfect place for this.

**Comment by mark-terminusdb** [comment]
Added a note block to the glossary definition of WOQL.

![image](https://user-images.githubusercontent.com/86666742/174487968-0d37f857-153c-49b4-adbd-ced9f49c37c5.png)
