### ISSUE TITLE
Document schema primitives

### ISSUE THREAD

**Issue by Tails** [terminusdb/terminusdb-docs#141]
I am writing a schema generator from Rust structs and was looking for a list of TDB schema primitives. 

It would be good to include the primitives in the Schema Reference for example.

I had to take them from here: https://github.com/terminusdb/terminus-dashboard/blob/f578c3004cbea315fc8f41c789cf57f59db01c39/src/html/datatypes/StringEditor.js but it is unclear if that is up-to-date.

**Comment by spl** [comment]
I agree that we need this. The current best reference I know of is [`base_type.pl`](https://github.com/terminusdb/terminusdb/blob/c9252810b8bf4ba66509bbcd558268ddfd4dbecb/src/core/triple/base_type.pl) in the `terminusdb` repo.

**Comment by spl** [comment]
Change the description for `xsd:decimal` to:

> Equivalent to `xsd:double`

**Comment by spl** [comment]
Except for the above change, the documentation is now found at:

https://terminusdb.com/docs/index/terminusx-db/reference-guides/terminusdb-data-types

**Comment by mark-terminusdb** [comment]
Changed `xsd:decimal` description and added the W3C specification for each date type where available.
