### ISSUE TITLE
Generated cli.md not appearing on GitBook

### ISSUE THREAD

**Issue by spl** [terminusdb/terminusdb-docs#143]
We now have docs generated automatically for the `terminusdb` CLI (#140). But I don't see the changes in the GitBook-rendered pages.

Compare:
* <https://github.com/terminusdb/terminusdb-docs/blob/main/readme/terminusx-db/reference-guides/cli.md>
* <https://terminusdb.com/docs/readme/terminusx-db/reference-guides/cli>

**Comment by Neelterminusdb** [comment]
Other than the headings i don't see any changes in the content. I suspect that the heading which is rendered is added by gitbook and not the mdfile. Maybe @mark-terminusdb will know this better

**Comment by spl** [comment]
@Neelterminusdb Aha! You're probably right. After a quick search, I'm guessing it comes from `summary.md`.

```sh
$ git grep 'TerminusDB Command Line Interface'
readme/terminusdb/install/install-from-source-code.md:* [Make the TerminusDB Command Line Interface](install-from-source-code.md#make-the-terminusdb-command-line-interface)
readme/terminusdb/install/install-from-source-code.md:### Make the TerminusDB Command Line Interface
readme/terminusdb/install/install-from-source-code.md:### The TerminusDB Command Line Interface
readme/terminusdb/install/install-from-source-code.md:[The TerminusDB Command Line Interface](../../terminusx-db/reference-guides/cli.md)
summary.md:      * [TerminusDB Command Line Interface (CLI)](readme/terminusx-db/reference-guides/cli.md)
```
