### ISSUE TITLE
Interface Guides: Dashboard - needs documentation

### ISSUE THREAD

**Issue by OJ423** [terminusdb/terminusdb-docs#162]
Need to understand if there are differences between TerminusDB and TerminusX dashboards.

Oliver can write up the docs here - Can Francesca let him know if there is any difference between the TerminusDB and TerminusX dashboards?

**Comment by Francesca-Bit** [comment]
Yes there is in access control, I'm preparing the screenshot and we can discuss tomorrow

**Comment by OJ423** [comment]
Dashboard overview included in docs now.
