### ISSUE TITLE
Restore doc generation from CLI

### ISSUE THREAD

**Issue by mark-terminusdb** [terminusdb/terminusdb-docs#17]
Update code that auto-generates this page.

https://github.com/terminusdb/terminusdb/blob/dev/docs/CLI.md

**Comment by spl** [comment]
* This needs to be done in CI.
* This should not be the `dev` branch. We should use the latest release branch, currently <https://github.com/terminusdb/terminusdb/blob/v10.0/docs/CLI.md>.
