### ISSUE TITLE
TerminusDB Docs: Existing page - Explanation->Closed world

### ISSUE THREAD

**Issue by mark-terminusdb** [terminusdb/terminusdb-docs#20]
Review content accuracy.

https://terminusdb.github.io/terminusdb/#/Explanation/CLOSED

**Comment by spl** [comment]
@GavinMendelGleason says, “Nuke it.” (Old link for reference: https://docs.terminusdb.com/v4.2/#/Explanation/CLOSED )

**Comment by spl** [comment]
@mark-terminusdb has not included it, yet, so done!
