### ISSUE TITLE
Mismatch in "Code: Define and initialize a WOQLClient" Section for javascript client

### ISSUE THREAD

**Issue by Neelterminusdb** [terminusdb/terminusdb-docs#21]
In the "Code: Define and initialize a WOQLClient" [snippet](https://docs.terminusdb.com/v10.0/#/terminusx/start-with-a-client?id=code-define-and-initialize-a-woqlclient) for javascript client have the variable *TerminusDBClient* defined in the first line but lines after it use *TerminusClient* as the variable name which doesnt match the name of the variable defined earlier, and can give error if a user is just copy pasting the snippet.

```javascript

const TerminusDBClient = require("@terminusdb/terminusdb-client");

const client = new TerminusClient.WOQLClient("https://cloud.terminusdb.com/cloudabc/",
                    {user:"user@email.com", organization:"cloudabc"})

//set the key as an environment variable.
client.setApiKey(process.env.TERMINUSDB_ACCESS_TOKEN)

client.connect().then((result)=>{
    console.log(result)
}).catch((err)=>{
    console.error(err);
})

```

**Comment by spl** [comment]
`TerminusDBClient` != `TerminusClient`

**Comment by Cheukting** [comment]
Fixed!
