### ISSUE TITLE
Do something with the woql-js docs

### ISSUE THREAD

**Issue by spl** [terminusdb/terminusdb-docs#27]
I saved the docs added to `main` in c1ae1dd56861c74a4e00146604423ff7bae9cf3d and added them to `next` in f7638f344ae8af6bb0937fcc0a2d650d0100e358. They are not linked anywhere, and I'm not sure what to do with them at the moment.

**Comment by matko** [comment]
@GavinMendelGleason can you review the current situation and make sure this can be closed?
