### ISSUE TITLE
References to OWL, old WOQL prefixes (scm, doc), and vio need to be updated

### ISSUE THREAD

**Issue by spl** [terminusdb/terminusdb-docs#49]
Part of this is done in https://github.com/terminusdb/terminusdb-docs/pull/32, but there is more.

Try searching the repository for these:

* https://github.com/terminusdb/terminusdb-docs/search?q=scm
* https://github.com/terminusdb/terminusdb-docs/search?q=vio
* https://github.com/terminusdb/terminusdb-docs/search?q=owl

**Comment by spl** [comment]
Specifically:

1. `doc` is now `@base` and `scm` is now `@schema`
2. Neither `@base` and `@schema` _need_ to be used as prefixes; however, they are allowed.

In our docs, we will:
1. not use the prefixes `@base` and `@schema` prefixes in general but
2. document that they can be used.

**Comment by spl** [comment]
Remove the snippet with the header [Code: WOQL variables using expanded syntax](https://terminusdb.com/docs/main/#/explanation/explanation-woql?id=code-woql-variables-using-expanded-syntax).

**Comment by mark-terminusdb** [comment]
# Files updated

The following file updated:

https://terminusdb.com/docs/main/#/explanation/explanation-woql

The following sub-sections require review:

- https://terminusdb.com/docs/main/#/explanation/explanation-woql?id=woql-prefixes (third code snippet removed and the preceding narrative changed accordingly.)
- https://terminusdb.com/docs/main/#/explanation/explanation-woql?id=prefixes-base-and-schema
- https://terminusdb.com/docs/main/#/explanation/explanation-woql?id=automatic-prefixes

# Files potentially requiring updates

The following files also use these prefixes. However, are these files still required?

- https://terminusdb.com/docs/main/#/how-to/how-to-add-date-and-time
- https://terminusdb.com/docs/main/#/how-to/how-to-load-turtle-files

**Comment by GavinMendelGleason** [comment]
* Add date and time needs to be updated for document interface - should be dropped now.
* Dopr the turtle load until it works

**Comment by GavinMendelGleason** [comment]
This should be removed - it is incorrect vocabulary and confusing.

```
WOQL functions

The JSON-LD form of WOQL supports a well-defined set of functions such as woql:Triple and woql:Regexp. In WOQL.js these functions are known as primitives. WOQL.js also adds several extensions to these primitives:

    Functions that are composed of multiple primitives.
    Functions that compose partial primitives and can be chained together.
    Simple helper functions to make it easier to format the arguments correctly. 
    ```

**Comment by mark-terminusdb** [comment]
Done and deployed to `main`:

**Removed:**

`WOQL functions` sub-section from https://terminusdb.com/docs/main/#/explanation/explanation-woql

**Removed the How-to items from the sidebar menu to the following links:**
- https://terminusdb.com/docs/main/#/how-to/how-to-add-date-and-time
- https://terminusdb.com/docs/main/#/how-to/how-to-load-turtle-files

**Comment by spl** [comment]
We will remove the section “TerminusDB standard prefixes” from `md/explanation/explanation-woql.md`.
