### ISSUE TITLE
"Add a schema" section description for Python client should be changed

### ISSUE THREAD

**Issue by Neelterminusdb** [terminusdb/terminusdb-docs#5]
In the beta [docs](https://docs.terminusdb.com/v10.0/#/terminusx/start-with-a-client?id=code-add-a-schema) for terminusX the section in getting started with client, the add schema description for python is not correct for what the snippet shows.

Screenshot for reference:
<img width="942" alt="Screenshot 2021-09-11 at 4 47 54 PM" src="https://user-images.githubusercontent.com/87318395/132946073-0033226d-4e45-46bd-a59a-8abac390b92e.png">

It should be changed to `Add the schema object to a document using commit or schema.commit`

**Comment by Cheukting** [comment]
Fixed
