### ISSUE TITLE
The "Define a schema" section code snippet for python throws error 

### ISSUE THREAD

**Issue by Neelterminusdb** [terminusdb/terminusdb-docs#6]
## Issue description:

When I use the code from the given [snippet](https://docs.terminusdb.com/v10.0/#/terminusx/start-with-a-client?id=code-define-a-schema) it throws an exception when it tries to compile the schema.

This is the given snippet in the documentation:
```python

from terminusdb_client.woqlschema import WOQLSchema, DocumentTemplate, LexicalKey

schema = WOQLSchema()

class Player(DocumentTemplate):
    _schema = schema
    _key = LexicalKey("name")
    name: str
    position: str
```
## Proposed Solution:
The `_key` parameter for the player schema should be changed to `_keys` in the snippet to create schema successfully as follows:  

```python
class Player(DocumentTemplate):
    _schema = schema
    _keys = LexicalKey("name")
    name: str
    position: str
 ```

**Comment by GavinMendelGleason** [comment]
In my opinion it should still be named _key as it is a unique key.

**Comment by Neelterminusdb** [comment]
Yes make sense, for it to work it should be changed in the python client.
@Cheukting can help maybe?

**Comment by spl** [comment]
Fixed!
