### ISSUE TITLE
CURL reference has no user/password

### ISSUE THREAD

**Issue by GavinMendelGleason** [terminusdb/terminusdb-docs#7]
There is no user or password in the curl command line examples. We need to show how this could be done and / or how to use JWT if the user is interested in for instance, building a client.

**Comment by spl** [comment]
The `curl` commands need the authorization header, `-H "Authorization: Bearer $TERMINUSDB_ACCESS_TOKEN"`, as well as perhaps showing the `export TERMINUSDB_ACCESS_TOKEN=...` at the top.

**Comment by AstroChelonian** [comment]
I have added the curl commands according to @spl 's commend below. I am testing the API for response for a token produced by

curl -s -X POST -H 'Accept: application/json' -H 'Content-Type: application/json' -u username:password   https://awsomelink.com | jq -r '.id_token'

to see that the the jwt works nicely.
