### ISSUE TITLE
Link to download the javascript script is pointing to old version

### ISSUE THREAD

**Issue by Neelterminusdb** [terminusdb/terminusdb-docs#72]
The [step](https://terminusdb.com/docs/main/#/install/install-javascript-client?id=download-the-script) which includes downloading and loading script of Javascript client is pointing to old version of the client which is 4.0 it should be updated to the latest version which is 10.0.1 https://unpkg.com/browse/@terminusdb/terminusdb-client@10.0.1/dist/

**Comment by spl** [comment]
It seems like <https://unpkg.com/browse/@terminusdb/terminusdb-client/dist/> redirects to the latest version. I suppose we should use that instead.

**Comment by Neelterminusdb** [comment]
Oh yes will make a pr for it

**Comment by spl** [comment]
This still needs to be fixed for `https://unpkg.com/browse/@terminusdb/terminusdb-client@4.3.1/dist/`.

**Comment by spl** [comment]
Fixed!
