### ISSUE TITLE
Missing links (404)

### ISSUE THREAD

**Issue by spl** [terminusdb/terminusdb-docs#8]
On <https://docs.terminusdb.com/v10.0/#/terminusx/documents?id=the-terminusdb-document-store>, the following are reported missing by the browser console:

* `/v10.0/md/terminusx/config/sidebar.md`
* `/v10.0/md/terminusx/Contact-Graph-Diagram.jpg`

**Comment by spl** [comment]
The sidebar 404 is fixed. It was just a matter of docsify looking for a subdirectory-local `sidebar.md` and not finding one, but it's nice to avoid the 404 anyway.

This leaves only the `Contact-Graph-Diagram.jpg`. @mark-terminusdb?

**Comment by mark-terminusdb** [comment]
Added `Contact-Graph-Diagram.jpg` to `documents.md`.

**Comment by spl** [comment]
Thanks!
